import React from "react";


const HomeTabbedNavigation = () => {
  return (
    <div className="container-fluid sp">
      <div className="row col-12 mx-auto cp mt-5 pt-3" data-aos="fade-up" data-aos-delay="100">
        <ul className="nav nav-pills nav-justified" id="pills-tab" role="tablist">
          <li className="nav-item" role="presentation">
            <button
              className="nav-link rounded-top text-uppercase active"
              id="pills-vision-tab"
              data-bs-toggle="pill"
              data-bs-target="#pills-vision"
              type="button"
              role="tab"
              aria-controls="pills-vision"
              aria-selected="true"
            >
              Vision
            </button>
          </li>
          <li className="nav-item" role="presentation">
            <button
              className="nav-link rounded-top text-uppercase"
              id="pills-mission-tab"
              data-bs-toggle="pill"
              data-bs-target="#pills-mission"
              type="button"
              role="tab"
              aria-controls="pills-mission"
              aria-selected="false"
            >
              Mission
            </button>
          </li>
          <li className="nav-item" role="presentation">
            <button
              className="nav-link rounded-top text-uppercase"
              id="pills-about-tab"
              data-bs-toggle="pill"
              data-bs-target="#pills-about"
              type="button"
              role="tab"
              aria-controls="pills-about"
              aria-selected="false"
            >
              About Us
            </button>
          </li>
        </ul>
        <div className="tab-content h-content rounded" id="pills-tabContent">
          <div
            className="tab-pane fade show active"
            id="pills-vision"
            role="tabpanel"
            aria-labelledby="pills-vision-tab"
          >
            <h4>Our Vision &amp; Value</h4>
            <h5>Our Vision</h5>
            <p>
              To emerge as the premier R&amp;D institution for the design,
              development, and deployment of world-class electronic and IT
              solutions for economic and human advancement.
            </p>
            <h5>Our Mission</h5>
            <ul>
              <li>Expand the frontiers of Electronics and Information Technology.</li>
              <li>Evolve technology solutions - architectures, systems and standards for nationally important problems.</li>
              <li>Achieve rapid and effective spread of knowledge by overcoming language barriers through application of technologies.</li>
              <li>Share experience and know-how to help build advanced competence in the areas of Electronics and Information Technology.</li>
              <li>Bring benefits of Electronics and Information Technology to society.</li>
              <li>Utilize the Intellectual Property generated by converting it to business opportunity.</li>
            </ul>
          </div>
          <div
            className="tab-pane fade"
            id="pills-mission"
            role="tabpanel"
            aria-labelledby="pills-mission-tab"
          >
            <h4>Mission Mode Programme</h4>
            <p>
              C-DAC with its focus in Advanced Computing is uniquely positioned
              to establish dependable and secure Exascale Ecosystem offering
              services in various domains.
            </p>
            <div className="row">
				<div className="col-md-3 col-sm-12 text-center">
					<img
						src = "https://cdac.in/img/exascale.png"
						alt="Custom Image"
						className="border border-5 shadow rounded-circle border-white"
					/>
					<h5 className="my-3">Exascale Computing Mission</h5>
				</div>
              <div className="col-md-3 col-sm-12 text-center">
                <img
                  src="https://cdac.in/img/quantom.png"
                  alt="Quantum Computing Mission Icon"
                  className="border border-5 shadow rounded-circle border-white"
                />
                <h5 className="my-3">Quantum Computing Mission</h5>
              </div>
              <div className="col-md-3 col-sm-12 text-center">
                <img
                  src="https://cdac.in/img/micro.png"
                  alt="Microprocessor and Strategic Electronics Mission Icon"
                  className="border border-5 shadow rounded-circle border-white"
                />
                <h5 className="my-3">Microprocessor and Strategic Electronics Mission</h5>
              </div>
              <div className="col-md-3 col-sm-12 text-center">
                <img
                  src="https://cdac.in/img/ioe.png"
                  alt="IoE, Dependable and Secure Computing Mission Icon"
                  className="border border-5 shadow rounded-circle border-white"
                />
                <h5 className="my-3">IoE, Dependable and Secure Computing Mission</h5>
              </div>
            </div>
          </div>
          <div
            className="tab-pane fade"
            id="pills-about"
            role="tabpanel"
            aria-labelledby="pills-about-tab"
          >
            <h4>About Us</h4>
            <p>
              Centre for Development of Advanced Computing (C-DAC) is the premier R&amp;D
              organization of the Ministry of Electronics and Information
              Technology (MeitY).
            </p>
            <ul>
              <li>The setting up of C-DAC in 1988 itself was to build Supercomputers in context of denial of import of Supercomputers by USA.</li>
              <li>
                C-DAC started building Indian Language Computing Solutions with
                the setting up of GIST group.
              </li>
              <li>
                Electronic Research and Development Centre of India (ER&amp;DCI)
                was brought under the Department of Electronics and Telecommunications.
              </li>
              <li>
                C-DAC's education &amp; training activities grew to meet the
                needs of Indian Industry.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomeTabbedNavigation;
